version: '3.8'

services:
  api:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/docs || exit 1"]
      interval: 30s
      timeout: 60s
      retries: 15
      start_period: 120s
    networks:
      - sms-fraud-network

  web:
    build: ./interface-web
    ports:
      - "8000:8000"
    volumes:
      - ./interface-web:/app
    depends_on:
      api:
        condition: service_healthy
    environment:
      - PYTHONUNBUFFERED=1
      - API_URL=http://api:8080
      - HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000 || exit 1"]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - sms-fraud-network

networks:
  sms-fraud-network:
    driver: bridge 